#name: "Build & Release"
#
#on:
#  pull_request:
#    branches:
#      - master
#  push:
#    branches:
#      - master
#      - work
#
#jobs:
#  build:
#    name: Build & Release
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '12'
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          architecture: x64
#      - run: flutter pub get
#      - run: flutter build apk --release --split-per-abi
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#        env:
#          JAVA_HOME: C:\hostedtoolcache\windows\Java_Zulu_jdk\12.0.2-3\x64
#          JAVA_HOME_12_X64: C:\hostedtoolcache\windows\Java_Zulu_jdk\12.0.2-3\x64
#          FLUTTER_ROOT: C:\hostedtoolcache\windows\flutter\stable-3.22.2-x64
#          PUB_CACHE: C:\Users\runneradmin\AppData\Local\Pub\Cache

#
#on: push
#name: Test, Build and Release apk
#jobs:
#  build:
#    name: Build APK
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          architecture: x64
#      - run: flutter pub get
#      - run: flutter build apk --debug --split-per-abi
#      - name: Push APK to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/debug/*.apk"
#          token: ${{ secrets.TOKEN }}


name: Flutter CI for Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: actions/setup-flutter@v2
        with:
          flutter-version: stable

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/app/outputs/apk/release/
            build/app/outputs/aab/release/

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}